defaults:
  - name: 쉼
    title: 힐링 오디오 서비스
    content: 쉼은 집중이나 휴식이 필요한 사람들에게 ASMR이나 클래식과 같은 오디오 컨텐츠를 제공합니다. 
    android: https://play.google.com/store/apps/details?id=co.shimm.app
    tags:
     - Node.js
     - Android
     - Retrofit2

  - name: 헤쳐모여 
    title: 운동 목표 기록 서비스
    content: 러닝, 사이클에 대한 개인의 운동 목표 설정, 기록, 공유 서비스를 제공합니다
    android: https://play.google.com/store/apps/details?id=com.prography.prography_pizza
    tags:
     - Node.js
     - Android

  - name:  DailyPicture
    title: 매일 일상의 변화 기록 
    content: 기록을 한 사진들을 일정 이상의 사진들이 기록되면, 영상으로 변환하여 변화를 한눈에 볼 수 있습니다.
    android: https://play.google.com/store/apps/details?id=org.techtown.dailypicture
    tags:
      - Android
      - Kotlin
      - Django
      - Docker

  - name: Just Select pizzA
    title: 토핑만 고르세요! 토핑에 맞는 피자를 찾아드립니다!
    content: 원하는 토핑을 도우 위에 얹으면 가장 비슷한 피자를 찾아주는 서비스
    tags:
      - Node.js
      - React
      - AWS
    website: http://jsa-pizza.coo.kr/
  - name: cogether
    title: 개발 관련 정보를 모아서 보여주는 서비스
    content: Cogether은 개발자들에게 필요한 컨퍼런스, 교육 및 동아리 정보를 모아서 한 눈에 볼 수 있는 서비스입니다.
    website: https://cogether.kr/
    tags:
      - Django
      - React

  - name: tingting
    title: 대학생 미팅 소개팅 앱
    content: 대학생을 위한 미팅 소개팅 모바일 서비스 플랫폼입니다
    tags:
      - Node.js
      - AWS
      - Android
      - ios
  - name: DDEP
    title: 딥러닝 기반 얼굴 모자이크 서비스
    content: 초상권 보호를 위한 얼굴 모자이크 서비스를 제공합니다.
    tags:
      - Computer Vision
      - Deep Learning
      - AWS
  - name: 개같하
    title: 개발 같이 하자!
    content: 개발 모임을 만드는 서비스를 제공합니다
    tags:
      - Django
      - React
      - AWS

tagmap:
  - tag: Github
    url: http://github.com/
  - tag: AWS
    url: http://aws.amazon.com/
  - tag: PostgreSql
    url: https://www.postgresql.org/
  - tag: MySQL
    url: http://www.mysql.com
  - tag: Docker
    url: https://docs.docker.com/
  - tag: Node.js
    url: https://nodejs.org/
  - tag: Retrofit
    url: https://github.com/square/retrofit
  - tag: Django
    url: https://www.djangoproject.com/
  - tag: React
    url: https://reactjs.org/